# -*- coding: utf-8 -*-
"""servidor_ia

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lmvZ0sINHSSwP_cIm9bizj82D3XUI3lv
"""

# servidor_ia.py — versión OpenAI
from fastapi import FastAPI
from pydantic import BaseModel
from openai import OpenAI
import os

app = FastAPI(title="Servidor IA Telemedicina - OpenAI GPT-4o-mini")

# Configurar cliente
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

class Solicitud(BaseModel):
    diagnostico: str
    probabilidad: float
    sintomas: list[str]

@app.post("/explicar")
def explicar(data: Solicitud):
    if data.probabilidad < 0.9:
        return {
            "estado": "incertidumbre",
            "mensaje": (
                f"La predicción tuvo solo {data.probabilidad*100:.1f}% de confianza. "
                "Se recomienda agregar más síntomas o consultar a un médico."
            )
        }

    prompt = (
        f"Paciente con {', '.join(data.sintomas)}.\n"
        f"Diagnóstico probable: {data.diagnostico} ({data.probabilidad*100:.1f}% de certeza).\n"
        "Eres un asistente médico empático y profesional. "
        "Explica qué es esta enfermedad, sus causas comunes y cuidados iniciales "
        "en lenguaje claro y comprensible para el paciente."
    )

    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": "Eres un asistente médico empático y claro."},
                {"role": "user", "content": prompt}
            ],
            max_tokens=250,
            temperature=0.7
        )
        texto = response.choices[0].message.content
        return {"estado": "exito", "explicacion": texto.strip()}
    except Exception as e:
        return {"estado": "error", "mensaje": f"Excepción: {str(e)}"}