# -*- coding: utf-8 -*-
"""servidor_ia

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lmvZ0sINHSSwP_cIm9bizj82D3XUI3lv
"""

# servidor_ia.py
from fastapi import FastAPI
from pydantic import BaseModel
import openai
import os

# 1️⃣ Crear app
app = FastAPI(title="Servidor IA Telemedicina")

# 2️⃣ Configurar API Key (Render usará variable de entorno)
openai.api_key = os.getenv("OPENAI_API_KEY")

# 3️⃣ Estructura de solicitud
class Solicitud(BaseModel):
    diagnostico: str
    probabilidad: float
    sintomas: list[str]

# 4️⃣ Endpoint principal
@app.post("/explicar")
def explicar(data: Solicitud):
    # Caso de baja confianza
    if data.probabilidad < 0.9:
        return {
            "estado": "incertidumbre",
            "mensaje": (
                f"La predicción tuvo solo {data.probabilidad*100:.1f}% de confianza. "
                "Se recomienda agregar más síntomas o consultar a un médico."
            )
        }

    # Prompt dinámico
    prompt = f"""
    Paciente con {', '.join(data.sintomas)}.
    Diagnóstico probable: {data.diagnostico} ({data.probabilidad*100:.1f}% de certeza).
    Eres un asistente médico empático y profesional.
    Explica brevemente qué es esta enfermedad,
    sus causas comunes y brinda una orientación inicial en lenguaje claro.
    """

    try:
        respuesta = openai.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=180
        )

        texto = respuesta.choices[0].message.content.strip()
        return {"estado": "exito", "explicacion": texto}

    except Exception as e:
        return {"estado": "error", "mensaje": f"Excepción: {str(e)}"}