# -*- coding: utf-8 -*-
"""servidor_ia

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lmvZ0sINHSSwP_cIm9bizj82D3XUI3lv
"""

# servidor_ia.py — versión OpenAI
from fastapi import FastAPI
from pydantic import BaseModel
from openai import OpenAI
import os

app = FastAPI(title="Servidor IA Telemedicina - OpenAI GPT-4o-mini")

# Configurar cliente
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

class Solicitud(BaseModel):
    diagnostico: str
    probabilidad: float
    sintomas: list[str]

@app.post("/explicar")
def explicar(data: Solicitud):
    """
    Recibe diagnóstico y probabilidad desde el modelo local de síntomas
    y genera una orientación médica con tono adaptado al nivel de confianza.
    """

    # Generar contexto dinámico según confianza
    if data.probabilidad < 0.8:
        tono = (
            "El modelo tiene una confianza moderada. "
            "Explica de forma breve y cautelosa, evitando afirmar con certeza. "
            "Usa expresiones como 'podría tratarse de' o 'es posible que sea'."
        )
    else:
        tono = (
            "El modelo tiene alta confianza. "
            "Explica con seguridad moderada y da recomendaciones iniciales claras."
        )

    # Prompt contextualizado
    prompt = (
        f"Paciente residente en la comuna Playa Delfín, zona rural costera del Guayas, Ecuador. "
        f"Presenta los siguientes síntomas: {', '.join(data.sintomas)}. "
        f"Diagnóstico probable: {data.diagnostico} ({data.probabilidad*100:.1f}% de certeza). "
        f"{tono} "
        "Adapta tus respuestas a un entorno caluroso y con recursos médicos limitados. "
        "Finaliza recordando que esta información no sustituye la consulta médica."
    )

    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": (
                    "Eres un asistente médico empático, que explica en lenguaje claro pero de forma breve y comprensible para el paciente, los posibles cuidados y prevención, "
                    "considerando las condiciones climáticas y de recursos médicos limitados."
                    "Responde en máximo tres párrafos, sin tecnicismos, con tono humano."
                )},
                {"role": "user", "content": prompt}
            ],
            max_tokens=400,
            temperature=0.6
        )

        texto = response.choices[0].message.content
        return {"estado": "exito", "explicacion": texto.strip()}

    except Exception as e:
        return {"estado": "error", "mensaje": f"Excepción: {str(e)}"}